/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;
import Abstracta.BD;
import Clases.Lineamiento;
import Listas.ListaLineamiento;
import Ventanas.GrillaAsignatura;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class NuevoLineamiento extends javax.swing.JFrame {
 private Lineamiento Lineamiento;
    /**
     * Creates new form NuevaAsig
     */
    public NuevoLineamiento() {
        initComponents();
            try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            
                 
            ResultSet rs3 = stmt.executeQuery("select CargoId,nombre from Cargo");
            //jCargo.removeAllItems();
            while (rs3.next()) {
                String aux1 = String.valueOf(rs3.getString(1)+" - "+rs3.getString(2));
                jCargo.addItem(aux1);
            }
            
           /* rs.close();
            rs3.close();
            stmt.close();
            con.close();*/
        } catch (Exception error) {
            System.out.println(error);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        txtc = new javax.swing.JTextField();
        btnCancelar1 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtc1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComisiones = new javax.swing.JComboBox();
        jHorasSemanales = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDedicacion = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jCantComisiones = new javax.swing.JComboBox();
        jCargo = new javax.swing.JComboBox();
        btnGrabar1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtc2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDedicacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Lineamiento");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcKeyTyped(evt);
            }
        });

        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnCancelar1.setText("Salir");
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnCancelar1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancelar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtc1KeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel14.setText("Comisiones");

        jComisiones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jHorasSemanales.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        jHorasSemanales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHorasSemanalesActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel15.setText("Horas Semanales");

        jLabel16.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel16.setText("Cantidad de Comisiones");

        jLabel17.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel17.setText("Dedicacion");

        jDedicacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1", "1.5", "2", "2.5" }));

        jLabel18.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel18.setText("Categoria");

        jCantComisiones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargoActionPerformed(evt);
            }
        });

        btnGrabar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/operacion.png"))); // NOI18N
        btnGrabar1.setText("Registrar");
        btnGrabar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGrabar1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnGrabar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGrabar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(42, 42, 42)
                                .addComponent(jComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(10, 10, 10)
                                .addComponent(jHorasSemanales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(312, 312, 312)
                        .addComponent(txtc1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(jCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCantComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)))
                        .addComponent(btnGrabar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtc1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHorasSemanales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jCantComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(btnGrabar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtc2KeyTyped(evt);
            }
        });

        jtDedicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Asignatura", "Categoria", "Condicion"
            }
        ));
        jtDedicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtDedicacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtDedicacion);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnGrabar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabar1ActionPerformed
        try {
            Connection cn = BD.getConnection();
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery("select max(LineamientoId) from Lineamiento");
            while (rs.next()) {
                txtc.setText(String.valueOf(rs.getInt(1)+1));
            }
            rs.close();
            stmt.close();
            cn.close();
            if(txtc.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Grabar");
            }
            else{
                int lineamientoId =Integer.parseInt( txtc.getText());
              
                String comisiones = (String) jComisiones.getSelectedItem();
                int co =Integer.parseInt(comisiones);
                
                String horaSemanal = (String) jHorasSemanales.getSelectedItem();
                int hs =Integer.parseInt(horaSemanal);
                
               
                String c = String.valueOf(jCargo.getModel().getSelectedItem());
                String numero2="";
                for (int i = 0; i < c.length(); i++) {
                    if (Character.isDigit(c.charAt(i))) {
                        numero2=numero2+c.charAt(i);
                    }
                }
                System.out.println("numeros2: " + numero2);
                int auxC;
                auxC = Integer.parseInt(numero2);
                
                String canComisiones = (String) jCantComisiones.getSelectedItem();
                int cc =Integer.parseInt(canComisiones);
                
                String dedicacion = (String) jDedicacion.getSelectedItem();
                float de =Float.parseFloat(dedicacion);
                
                
                Lineamiento l= new Lineamiento();
                l.setLineamientoId(lineamientoId);
                
                l.setComisiones(co);
                l.setHoraSemanal(horaSemanal);
                l.setCategoria(auxC);
                l.setCanComisiones(cc);
                l.setDedicacion(de);
                l.altas();
                buscar();
                JOptionPane.showMessageDialog(null,"Una nueva Categoria ha sido Registrada");
                
                DefaultTableModel modelo = (DefaultTableModel) GrillaLineamientos.jtLineamientos.getModel();
        
        
         int i=0; 
         i=i+1;
         Object[]  dato=new Object[3];
         
            dato[0]=lineamientoId;
            dato[1]=comisiones;
            dato[2]=horaSemanal;
     
            
            modelo.addRow(dato);
           GrillaLineamientos.jtLineamientos.setModel(modelo);
           GrillaLineamientos.jtLineamientos.editCellAt(0, 2);
                          
                
        }
        } catch (Exception error) {
            System.out.println(error);
        }  
        
    }//GEN-LAST:event_btnGrabar1ActionPerformed

    private void txtc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc1KeyTyped

    private void txtcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtcKeyTyped

    private void jHorasSemanalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHorasSemanalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHorasSemanalesActionPerformed

    private void jtDedicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtDedicacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDedicacionMouseClicked

    private void txtc2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc2KeyTyped

    private void jCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargoActionPerformed
        /*try {

            Connection con3 = BD.getConnection();
            Statement stmt3 = con3.createStatement();
            ResultSet rs3 = stmt3.executeQuery("select CargoId,nombre from Cargo");
            jCargo.removeAllItems();
            while (rs3.next()) {
                String aux = String.valueOf(rs3.getString(1)+" - "+rs3.getString(2));
                jCargo.addItem(aux);
            }
            rs3.close();
            stmt3.close();
            con3.close();
        } catch (Exception error) {
            System.out.println(error);
        }
        */
    }//GEN-LAST:event_jCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoLineamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoLineamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoLineamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoLineamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoLineamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnGrabar1;
    private javax.swing.JComboBox jCantComisiones;
    private javax.swing.JComboBox jCargo;
    private javax.swing.JComboBox jComisiones;
    private javax.swing.JComboBox jDedicacion;
    private javax.swing.JComboBox jHorasSemanales;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtDedicacion;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtc1;
    private javax.swing.JTextField txtc2;
    // End of variables declaration//GEN-END:variables
  void mostrar() {
         try{
             ListaLineamiento lista = new ListaLineamiento(Lineamiento.leer());
             DefaultTableModel info=new DefaultTableModel();
             info.addColumn("LineamientoId");
             info.addColumn("Comisiones");
             info.addColumn("horaSemanal");
             info.addColumn("canComision");
             info.addColumn("Cargo");
             info.addColumn("dedicacion");
             
             for(int i=0; i<lista.getListaLineamiento().size();i++){
                Object[]fila=new Object[]{
                lista.getListaLineamiento().get(i).getLineamientoId(),
                lista.getListaLineamiento().get(i).getComisiones(),    
                lista.getListaLineamiento().get(i).getHoraSemanal(),
                lista.getListaLineamiento().get(i).getCanComisiones(),
                lista.getListaLineamiento().get(i).getCategoria(),
                lista.getListaLineamiento().get(i).getDedicacion()
                
                
                };
                 info.addRow(fila);
            }
                 jtDedicacion.setModel(info);
        }catch(Exception a){
            a.printStackTrace();
        }
}
   public void buscar(){
     try{
        DefaultTableModel info=new DefaultTableModel();
        this.jtDedicacion.setModel(info);
        Connection cn = BD.getConnection();
        Statement stmt = cn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT c.Nombre,CantidadComision, l.Dedicacion FROM mydb.Lineamiento l inner join mydb.cargo c on l.Cargo_CargoId = c.CargoId;");
        //Obteniendo la informacion de las columnas que estan siendo consultadas
        ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
        //La cantidad de columnas que tiene la consulta
        int cantidadColumnas = rsMd.getColumnCount();
        //Establecer como cabezeras el nombre de las colimnas
        for (int i = 1; i <= cantidadColumnas; i++) {
        info.addColumn(rsMd.getColumnLabel(i));
        }
        //Creando las filas para el JTable
        while (rs.next()) {
        Object[] fila = new Object[cantidadColumnas];
        for (int i = 0; i < cantidadColumnas; i++) {
         fila[i]=rs.getObject(i+1);
        }
        info.addRow(fila);
        }
        rs.close();
        cn.close();
        }
        catch (Exception ex) {
             ex.printStackTrace();
        }   
    }
}
