/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Listas.ListaCargoDocente;
import Ventanas.GrillaDocente;
import Clases.Docente;
import Clases.CargoDocente;
import Abstracta.BD;
import Ventanas.GrillaAsignatura;
import Horario.ListaDocentes;
import Clases.Menu;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class NuevoDocente extends javax.swing.JFrame {
private CargoDocente CargoDocente;    
public static javax.swing.JDesktopPane escritorio;
//SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
    //Date fecha = null;

    /**
     * Creates new form NuevoDoc
     */
    public NuevoDocente() {
        CargoDocente=new CargoDocente();
        initComponents();
         this.setLocationRelativeTo(null);
         txtc.setVisible(false);
         txtc1.setVisible(false);
   
         try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            
            ResultSet rs = stmt.executeQuery("select AsignaturaId,nombre from Asignatura");
            while (rs.next()) {
                String aux = String.valueOf(rs.getString(1)+" - "+rs.getString(2));
                jAsignatura.addItem(aux);  
            }
            
            ResultSet rs3 = stmt.executeQuery("select CargoId,nombre from Cargo");
            //jCargo.removeAllItems();
            while (rs3.next()) {
                String aux1 = String.valueOf(rs3.getString(1)+" - "+rs3.getString(2));
                jCargo.addItem(aux1);
            }
            
           /* rs.close();
            rs3.close();
            stmt.close();
            con.close();*/
        } catch (Exception error) {
            System.out.println(error);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jNivel = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jAsignatura = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jCargo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCargoDocente = new javax.swing.JTable();
        btnAgregarCargo = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtc3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCondicion = new javax.swing.JComboBox();
        txtc = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txto = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtc1 = new javax.swing.JTextField();
        txtn = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        txte = new javax.swing.JTextField();
        btnAgregarDocente = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Docente");

        jLabel1.setText("Nivel");

        jNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));
        jNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNivelActionPerformed(evt);
            }
        });

        jLabel2.setText("Asignatura");

        jLabel3.setText("Cargo");

        jCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargoActionPerformed(evt);
            }
        });

        jtCargoDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Asignatura", "Categoria", "Condicion"
            }
        ));
        jtCargoDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCargoDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCargoDocente);

        btnAgregarCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/operacion.png"))); // NOI18N
        btnAgregarCargo.setText("Agregar");
        btnAgregarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCargoActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtc3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtc3KeyTyped(evt);
            }
        });

        jLabel4.setText("Condicion");

        jCondicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Interino", "Ordinario" }));

        txtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcActionPerformed(evt);
            }
        });
        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel22.setText("E-mail");

        jLabel24.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel24.setText("Legajo");

        jLabel25.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel25.setText("Observacion");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel23.setText("Nombre");

        txtc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtc1ActionPerformed(evt);
            }
        });
        txtc1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtc1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtc1KeyTyped(evt);
            }
        });

        txtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnActionPerformed(evt);
            }
        });
        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel21.setText("Fecha de Contrato");

        btnAgregarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/operacion.png"))); // NOI18N
        btnAgregarDocente.setText("Agregar");
        btnAgregarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtc1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10))
                                .addGroup(jPanel9Layout.createSequentialGroup()
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel23))
                                    .addGap(4, 4, 4)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(46, 46, 46)
                                .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel23))
                            .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAgregarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jNivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgregarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed

    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased

    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnActionPerformed

    private void txtnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyReleased

    }//GEN-LAST:event_txtnKeyReleased

    private void txtnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyTyped

    }//GEN-LAST:event_txtnKeyTyped

    private void jtCargoDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCargoDocenteMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtCargoDocenteMouseClicked

    private void btnAgregarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDocenteActionPerformed
        try {
            Connection cn = BD.getConnection();
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery("select max(DocenteId) from Docente");
            while (rs.next()) {
                txtc.setText(String.valueOf(rs.getInt(1)+1));
            }
            rs.close();
            stmt.close();
            cn.close();
        } catch (Exception error) {
            System.out.println(error);
        }
        if(txtc.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Grabar");
            }
            else{
                int DocenteId =Integer.parseInt(txtc.getText());
                int Legajo =Integer.parseInt( txtCodigo.getText());
                String nombre = txtn.getText();
                String email= txte.getText();                
                     
              
                String condicion = (String) jCondicion.getSelectedItem();
                Date fecha = jDateChooser2.getDate();
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                System.out.println("fecha "+formato.format(fecha));
                String s = formato.format(fecha);
                String observacion = txto.getText();
                Docente d= new Docente();
                d.setDocenteId(DocenteId);
                System.out.println("DocenteId"+DocenteId);
                d.setLegajo(Legajo);
                System.out.println("legajo"+Legajo);
                d.setNombre(nombre);
                System.out.println("nombre"+nombre);
                d.setEmail(email);              
                System.out.println("email"+email);
                d.setFecha(s);
                System.out.println("fecha"+fecha);
                d.setObservacion(observacion);
                System.out.println("Obs"+observacion);
                d.setCondicion(condicion);
                System.out.println("cond"+condicion);
                d.altas();
                System.out.println("alta");
            
                JOptionPane.showMessageDialog(null,"Un nuevo Docente ha sido Registrado");
            DefaultTableModel modelo = (DefaultTableModel) GrillaDocente.jtDatosDocente.getModel();
        
        
         int i=0; 
         i=i+1;
         Object[]  dato=new Object[6];

            dato[0]=Legajo;
            dato[1]=nombre;
            dato[2]=email;
            dato[3]=s;
            dato[4]=condicion;
            dato[5]=observacion;
           
            modelo.addRow(dato);
           GrillaDocente.jtDatosDocente.setModel(modelo);
           GrillaDocente.jtDatosDocente.editCellAt(0, 2);
          }
    }//GEN-LAST:event_btnAgregarDocenteActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcActionPerformed

    private void txtcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcKeyReleased

    private void txtcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcKeyTyped

    private void btnAgregarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCargoActionPerformed

           
        try {
            Connection cn = BD.getConnection();
            Statement stmt = cn.createStatement();
             ResultSet rs1 = stmt.executeQuery("select max(CargoDocenteId) from cargo_has_docente");
            while (rs1.next()) {
            txtc1.setText(String.valueOf(rs1.getInt(1)+1));
            }
              
            if(txtc.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Grabar");
            }
            else{
                int DocenteId =Integer.parseInt(txtc.getText());
                
                String asig =String.valueOf(jAsignatura.getModel().getSelectedItem());
                String numero="";
                for (int i = 0; i < asig.length(); i++) {
                    if (Character.isDigit(asig.charAt(i))) {
                        numero=numero+asig.charAt(i);
                    }
                }
                System.out.println("numeros: " + numero);
                int auxA;
                auxA = Integer.parseInt(numero);     
                String c = String.valueOf(jCargo.getModel().getSelectedItem());
                String numero2="";
                for (int i = 0; i < c.length(); i++) {
                    if (Character.isDigit(c.charAt(i))) {
                        numero2=numero2+c.charAt(i);
                    }
                }
                System.out.println("numeros2: " + numero2);
                int auxC;
                auxC = Integer.parseInt(numero2);
           
            
                int CargoDocenteId =Integer.parseInt( txtc1.getText());
                CargoDocente cd= new CargoDocente();
                cd.setCargoDocenteId(CargoDocenteId);
                System.out.println("CargodocenteID "+CargoDocenteId);
                cd.setDocenteId(DocenteId);               
                System.out.println("DocenteId "+DocenteId);
                cd.setAsignaturaId(auxA);
                System.out.println("AsignaturaId "+auxA);
                cd.setCargoId(auxC);
                System.out.println("CargoId "+auxC);
                cd.altas();
                buscar();
                JOptionPane.showMessageDialog(null,"Un nuevo Cargo Docente ha sido Registrado");
           
          }
        } catch( Exception ex){
                System.out.println(ex +"asdasd"); 
           
        }              
       
        
    }//GEN-LAST:event_btnAgregarCargoActionPerformed

    private void jNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNivelActionPerformed
   try {
             
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            String ni = (String) jNivel.getSelectedItem();
            int nivel =Integer.parseInt(ni);
            ResultSet rs = stmt.executeQuery("select AsignaturaId,nombre from Asignatura where nivel="+nivel);
            jAsignatura.removeAllItems();
            while (rs.next()) {
                String aux = String.valueOf(rs.getString(1)+" - "+rs.getString(2));
                jAsignatura.addItem(aux);       
            }
       
        } catch (Exception error) {
            System.out.println(error);
        }
    }//GEN-LAST:event_jNivelActionPerformed

    private void txtc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc1ActionPerformed

    private void txtc1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc1KeyReleased

    private void txtc1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc1KeyTyped

    private void jCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargoActionPerformed
/*try {
             
            Connection con3 = BD.getConnection();
            Statement stmt3 = con3.createStatement();
            ResultSet rs3 = stmt3.executeQuery("select CargoId,nombre from Cargo");
            jCargo.removeAllItems();
            while (rs3.next()) {
                String aux = String.valueOf(rs3.getString(1)+" - "+rs3.getString(2));
                jCargo.addItem(aux);       
            }
            rs3.close();
            stmt3.close();
            con3.close();
        } catch (Exception error) {
            System.out.println(error);
        }
*/
    }//GEN-LAST:event_jCargoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtc3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtc3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NuevoDocente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCargo;
    private javax.swing.JButton btnAgregarDocente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox jAsignatura;
    private javax.swing.JComboBox jCargo;
    private javax.swing.JComboBox jCondicion;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox jNivel;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtCargoDocente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtc1;
    private javax.swing.JTextField txtc3;
    private javax.swing.JTextField txte;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txto;
    // End of variables declaration//GEN-END:variables
     private void filtrar() {
     try{
        CargoDocente cd = new CargoDocente();
        ListaCargoDocente lista = new ListaCargoDocente(CargoDocente.filtrar());
        DefaultTableModel info=new DefaultTableModel();
        info.addColumn("Asignatura");
        info.addColumn("Cargo");
        
        CargoDocente.setCargoDocenteId(Integer.parseInt(txtc1.getText()));
        if(CargoDocente.buscar())
            for(int i=0; i<lista.getListaCargoDocente().size();i++){
                Object[]fila=new Object[]{
                lista.getListaCargoDocente().get(i).getAsignaturaId(),
                lista.getListaCargoDocente().get(i).getCargoId()
               
        };
            info.addRow(fila);
          }
            jtCargoDocente.setModel(info);
    }catch(Exception a){
      a.printStackTrace();
      }
  }
     public void buscar(){
     try{
        DefaultTableModel info=new DefaultTableModel();
        this.jtCargoDocente.setModel(info);
        Connection cn = BD.getConnection();
        Statement stmt = cn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT a.Nivel,a.Nombre,d.Condicion,c.Nombre FROM mydb.cargo_has_docente cd inner join mydb.asignatura a on cd.Asignatura_AsignaturaId=a.AsignaturaId inner join mydb.Docente d on d.DocenteId=cd.Docente_DocenteId inner join mydb.cargo c on c.CargoId=cd.Cargo_CargoId where cd.Docente_DocenteId="+txtc.getText());
        //Obteniendo la informacion de las columnas que estan siendo consultadas
        ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
        //La cantidad de columnas que tiene la consulta
        int cantidadColumnas = rsMd.getColumnCount();
        //Establecer como cabezeras el nombre de las colimnas
        for (int i = 1; i <= cantidadColumnas; i++) {
        info.addColumn(rsMd.getColumnLabel(i));
        }
        //Creando las filas para el JTable
        while (rs.next()) {
        Object[] fila = new Object[cantidadColumnas];
        for (int i = 0; i < cantidadColumnas; i++) {
         fila[i]=rs.getObject(i+1);
        }
        info.addRow(fila);
        }
        rs.close();
        cn.close();
        }
        catch (Exception ex) {
             ex.printStackTrace();
        }   
    }
}