/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Clases.PlantaDocente;
import Listas.ListaCargoDocente;
import Clases.CargoDocente;
import Abstracta.BD;
import static Ventanas.GrillaPlantaDocenteReal.txtId;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class NuevaPlantaDocenteReal extends javax.swing.JFrame {
private CargoDocente CargoDocente;    
//SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
    //Date fecha = null;

    /**
     * Creates new form NuevoDoc
     */
    public NuevaPlantaDocenteReal() {
        CargoDocente=new CargoDocente();
        initComponents();
         this.setLocationRelativeTo(null);
         txtc.setVisible(false);
         txtCD.setVisible(false);
         txtCodigoAsignatura.setVisible(false);
         //txtc1.setVisible(false);
         
      
      //  System.out.println("codi:"+codigoAsignatura);
       // System.out.println("txtId:"+txtId.getText());
    //    System.out.println("CODIGO:"+txtCodigoAsignatura.getText());
   
         try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs2 = stmt.executeQuery("SELECT Cargo_CargoId,c.Nombre FROM mydb.asignatura a inner join mydb.cargo_has_docente cd on a.AsignaturaId =cd.Asignatura_AsignaturaId inner join mydb.cargo c on c.CargoId = cd.Cargo_CargoId where Codigo='"+txtId.getText()+"'");
            //jCargo.removeAllItems();
            while (rs2.next()) {
                String aux1 = String.valueOf(rs2.getString(1)+" - "+rs2.getString(2));
                jCargo.addItem(aux1);
            }
            ResultSet rs3 = stmt.executeQuery("SELECT d.DocenteId,d.Nombre FROM mydb.asignatura a inner join mydb.cargo_has_docente cd on a.AsignaturaId =cd.Asignatura_AsignaturaId inner join mydb.cargo c on c.CargoId = cd.Cargo_CargoId inner join mydb.docente d on d.DocenteId=cd.Docente_DocenteId where Codigo='"+txtId.getText()+"'");
            while (rs3.next()) {
                String aux2 = String.valueOf(rs3.getString(1)+" - "+rs3.getString(2));
                jDocente.addItem(aux2);
            }
           /* rs.close();
            rs3.close();
            stmt.close();
            con.close();*/
        } catch (Exception error) {
            System.out.println(error);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jCargo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCargoDocente = new javax.swing.JTable();
        btnAgregarCargo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        txtcomision = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtDedicacion = new javax.swing.JTextField();
        jDocente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtc = new javax.swing.JTextField();
        txtCodigoAsignatura = new javax.swing.JTextField();
        txtCD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nueva Planta Docente");

        jLabel3.setText("Cargo");

        jCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCargoActionPerformed(evt);
            }
        });

        jtCargoDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Categoria", "Comsiones", "Dedicaciones", "Docente"
            }
        ));
        jtCargoDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCargoDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCargoDocente);

        btnAgregarCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/operacion.png"))); // NOI18N
        btnAgregarCargo.setText("Agregar");
        btnAgregarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCargoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Salir");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel23.setText("Comisiones");

        txtcomision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcomisionActionPerformed(evt);
            }
        });
        txtcomision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcomisionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcomisionKeyTyped(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Levenim MT", 0, 11)); // NOI18N
        jLabel26.setText("Dedicaciones");

        txtDedicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDedicacionActionPerformed(evt);
            }
        });
        txtDedicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDedicacionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDedicacionKeyTyped(evt);
            }
        });

        jDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDocenteActionPerformed(evt);
            }
        });

        jLabel1.setText("Docente:");

        txtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcActionPerformed(evt);
            }
        });
        txtc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcKeyTyped(evt);
            }
        });

        txtCodigoAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoAsignaturaActionPerformed(evt);
            }
        });
        txtCodigoAsignatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoAsignaturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoAsignaturaKeyTyped(evt);
            }
        });

        txtCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCDActionPerformed(evt);
            }
        });
        txtCD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDedicacion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(txtcomision, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txtCodigoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnAgregarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtcomision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel26))
                    .addComponent(txtDedicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarCargo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtCargoDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCargoDocenteMouseClicked
  
    }//GEN-LAST:event_jtCargoDocenteMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCargoActionPerformed

           
        try {
            Connection cn = BD.getConnection();
            Statement stmt = cn.createStatement();
             ResultSet rs1 = stmt.executeQuery("select max(PlantaDocenteId) from PlantaDocente");
            while (rs1.next()) {
            txtc.setText(String.valueOf(rs1.getInt(1)+1));
            }
              
            if(txtc.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Ingrese un Codigo para Grabar");
            }
            else{
                  String c = String.valueOf(jCargo.getModel().getSelectedItem());
                String numero2="";
                for (int i = 0; i < c.length(); i++) {
                    if (Character.isDigit(c.charAt(i))) {
                        numero2=numero2+c.charAt(i);
                    }
                }
                System.out.println("numeros2: " + numero2);
                int auxC = Integer.parseInt(numero2);
                
             String a= String.valueOf(jDocente.getModel().getSelectedItem());
                String numero1="";
                for (int i = 0; i < a.length(); i++) {
                    if (Character.isDigit(a.charAt(i))) {
                        numero1=numero1+a.charAt(i);
                    }
                }
                System.out.println("numeros1: " + numero1);
                int auxD= Integer.parseInt(numero1);
                
             
              
                
                ResultSet rs4 = stmt.executeQuery("SELECT cd.cargoDocenteId FROM mydb.asignatura a inner join mydb.cargo_has_docente cd on a.AsignaturaId =cd.Asignatura_AsignaturaId inner join mydb.cargo c on c.CargoId = cd.Cargo_CargoId inner join mydb.docente d on d.DocenteId=cd.Docente_DocenteId where c.CargoId='"+auxC+"' and d.DocenteId='"+auxD+"'");
                while(rs4.next()){
                txtCD.setText(String.valueOf(rs4.getString(1)));
                               System.out.println("txtCD:"+rs4.getString(1));
                int comision = Integer.parseInt(txtcomision.getText());
                float dedicacion =Float.parseFloat(txtDedicacion.getText());
                int auxCD = Integer.parseInt(txtCD.getText());
                int PlantaDocenteId =Integer.parseInt( txtc.getText());
                PlantaDocente pd= new PlantaDocente();
                pd.setPlantaDocenteId(PlantaDocenteId);
                pd.setCargoDocenteId(auxCD);
                pd.setComisiones(comision);
                pd.setDedicaciones(dedicacion);
                pd.setTipo("Real");
                pd.altas();
                buscar();
                
                JOptionPane.showMessageDialog(null,"Un nuevo Cargo Docente ha sido Registrado");
                }
          }
        } catch( Exception ex){
                System.out.println(ex);
        }              
    }//GEN-LAST:event_btnAgregarCargoActionPerformed

    private void jCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCargoActionPerformed
 
    }//GEN-LAST:event_jCargoActionPerformed

    private void txtcomisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcomisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcomisionActionPerformed

    private void txtcomisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomisionKeyReleased

    }//GEN-LAST:event_txtcomisionKeyReleased

    private void txtcomisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcomisionKeyTyped

    }//GEN-LAST:event_txtcomisionKeyTyped

    private void txtDedicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDedicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedicacionActionPerformed

    private void txtDedicacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDedicacionKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedicacionKeyReleased

    private void txtDedicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDedicacionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDedicacionKeyTyped

    private void jDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDocenteActionPerformed
   
    }//GEN-LAST:event_jDocenteActionPerformed

    private void txtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcActionPerformed

    private void txtcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcKeyReleased

    private void txtcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcKeyTyped

    private void txtCodigoAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAsignaturaActionPerformed

    private void txtCodigoAsignaturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoAsignaturaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAsignaturaKeyReleased

    private void txtCodigoAsignaturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoAsignaturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoAsignaturaKeyTyped

    private void txtCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCDActionPerformed

    private void txtCDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCDKeyReleased

    private void txtCDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPlantaDocenteReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPlantaDocenteReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPlantaDocenteReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPlantaDocenteReal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NuevaPlantaDocenteReal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCargo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox jCargo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JComboBox jDocente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtCargoDocente;
    public static javax.swing.JTextField txtCD;
    public static javax.swing.JTextField txtCodigoAsignatura;
    private javax.swing.JTextField txtDedicacion;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txtcomision;
    // End of variables declaration//GEN-END:variables
     private void filtrar() {
     try{
        CargoDocente cd = new CargoDocente();
        ListaCargoDocente lista = new ListaCargoDocente(CargoDocente.filtrar());
        DefaultTableModel info=new DefaultTableModel();
        info.addColumn("Asignatura");
        info.addColumn("Cargo");
        
        CargoDocente.setCargoDocenteId(Integer.parseInt(txtCodigoAsignatura.getText()));
        if(CargoDocente.buscar())
            for(int i=0; i<lista.getListaCargoDocente().size();i++){
                Object[]fila=new Object[]{
                lista.getListaCargoDocente().get(i).getAsignaturaId(),
                lista.getListaCargoDocente().get(i).getCargoId()
               
        };
            info.addRow(fila);
          }
            jtCargoDocente.setModel(info);
    }catch(Exception a){
      a.printStackTrace();
      }
  }
     public void buscar(){
     try{
        DefaultTableModel info=new DefaultTableModel();
        this.jtCargoDocente.setModel(info);
        Connection cn = BD.getConnection();
        Statement stmt = cn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT c.Nombre,pd.Comisiones,pd.Dedicaciones,d.Nombre FROM mydb.plantadocente pd inner join mydb.cargo_has_docente cd on pd.CargohasDocente_CargoDocenteId=cd.CargoDocenteId inner join mydb.docente d on cd.Docente_DocenteId=d.DocenteId inner join mydb.cargo c on c.CargoId=cd.Cargo_CargoId");
        //Obteniendo la informacion de las columnas que estan siendo consultadas
        ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
        //La cantidad de columnas que tiene la consulta
        int cantidadColumnas = rsMd.getColumnCount();
        //Establecer como cabezeras el nombre de las colimnas
        for (int i = 1; i <= cantidadColumnas; i++) {
        info.addColumn(rsMd.getColumnLabel(i));
        }
        //Creando las filas para el JTable
        while (rs.next()) {
        Object[] fila = new Object[cantidadColumnas];
        for (int i = 0; i < cantidadColumnas; i++) {
         fila[i]=rs.getObject(i+1);
        }
        info.addRow(fila);
        }
        rs.close();
        cn.close();
        }
        catch (Exception ex) {
             ex.printStackTrace();
        }   
    }
}